"""Add Coach Studio Models

Revision ID: 1fb2fe8902b9
Revises: ae37583685d8
Create Date: 2026-04-27 14:32:17.713684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb2fe8902b9'
down_revision: Union[str, Sequence[str], None] = 'ae37583685d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_configs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('config_key', sa.String(length=255), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_configs_config_key'), 'coach_configs', ['config_key'], unique=True)
    
    op.create_table('coach_prompt_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('published_by', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_number')
    )
    
    op.create_table('predefined_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trigger_name', sa.String(length=255), nullable=False),
    sa.Column('trigger_keywords', sa.JSON(), nullable=False),
    sa.Column('match_mode', sa.String(length=50), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('predefined_responses')
    op.drop_table('coach_prompt_versions')
    op.drop_index(op.f('ix_coach_configs_config_key'), table_name='coach_configs')
    op.drop_table('coach_configs')
    # ### end Alembic commands ###
