"""Drop mood add announcements

Revision ID: caf978efa906
Revises: 1fb2fe8902b9
Create Date: 2026-05-19 11:45:39.464346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caf978efa906'
down_revision: Union[str, Sequence[str], None] = '1fb2fe8902b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('action_text', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('target_audience', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement_dismissals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('announcement_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    pass
    pass
    op.drop_table('overwhelmed_events')
    op.drop_index('ix_mood_check_ins_user_created', table_name='mood_check_ins')
    op.drop_index('ix_mood_check_ins_user_id', table_name='mood_check_ins')
    op.drop_table('mood_check_ins')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mood_check_ins',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('mood', sa.VARCHAR(length=11), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mood_check_ins_user_id', 'mood_check_ins', ['user_id'], unique=False)
    op.create_index('ix_mood_check_ins_user_created', 'mood_check_ins', ['user_id', 'created_at'], unique=False)
    op.create_table('overwhelmed_events',
    sa.Column('id', sa.CHAR(length=32), nullable=False),
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('nudges_paused_until', sa.DATETIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_overwhelmed_events_user_paused', 'overwhelmed_events', ['user_id', 'nudges_paused_until'], unique=False)
    op.create_index('ix_overwhelmed_events_user_id', 'overwhelmed_events', ['user_id'], unique=False)
    op.drop_table('announcement_dismissals')
    op.drop_table('announcements')
    # ### end Alembic commands ###
